name: readme
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch: # allows manual triggering
jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - name: write README.md
        run: |
          git fetch origin 'refs/tags/*:refs/tags/*'
          nix develop .#githubActions --command echo \
            $(nix flake metadata --quiet --json) \
            $(nix flake show --all-systems --quiet --json) \
            $(git tag | jq -R . | jq -s 'reduce .[] as $i ({tags: []}; .tags += [$i])') \
            | jq -s add > .github/workflows/data.json
          nix develop .#githubActions --command j2 --customize .github/workflows/customize.py -o README.md .github/workflows/README.md.j2 .github/workflows/data.json
      - name: commit changes
        run: |
          git config user.name "Nix Bot"
          git config user.email "<>"
          git checkout -b "${GITHUB_WORKFLOW}-${GITHUB_JOB}-${GITHUB_REF_TYPE}-${GITHUB_RUN_NUMBER}"
          git add README.md
          git commit -m "[nix] Update README.md"
          git push -u origin "${GITHUB_WORKFLOW}-${GITHUB_JOB}-${GITHUB_REF_TYPE}-${GITHUB_RUN_NUMBER}"
      - name: create pull request
        run: gh pr create -l actions -l bot --title "[readme/nix] Update README.md" --body "[bot] [readme/nix] Update README.md"
        env:
          GH_TOKEN: ${{ github.token }}
