name: check
on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual triggering
jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: DeterminateSystems/flake-checker-action@v9
      - run: nix flake check --all-systems
